### PR TITLE
feat: add isDeleting prop to disable select options when deleting

### PR DESCRIPTION
**Pull request by yurii-korolchuk**

### CODE REVIEW

**Review by sergdeev — APPROVED** [review]

**Comment by kaliahinartem** [comment]
You can just pass "isDisabled" prop
What's the added value of "isDeleted"? It does the same

**Comment by yurii-korolchuk** [comment]
> You can just pass "isDisabled" prop What's the added value of "isDeleted"? It does the same

I've tried using isDisabled prop, but the problem I've stumble upon was that is completely closes the select, when I just want it to disable options but not the whole select

**Comment by yurii-korolchuk** [comment]
Screen Recording 2022-05-23 at 13 49 30
Screen Recording 2022-05-23 at 13 46 04

**Comment by kaliahinartem** [comment]
@yurii-korolchuk then use this?
image

**Comment by yurii-korolchuk** [comment]
> @yurii-korolchuk then use this? image

(facepalm) should've made a better research, thanks, will close this PR

**Pull request closed without merging**
